### ISSUE TITLE
megalinter/megalinter:v5 not running linters in GitlabCI

### ISSUE THREAD

**Issue by guruvamsichintala5** [megalinter/megalinter#1054]
Configured new megalinter:v5  image in GitlabCI (need to use megalinter/megalinter:v5 image )

.gitlabCI.yml

````yaml
stages:
  - mega-linter

mega-linter-job:
  stage: mega-linter
  tags:
    - rancher2
  image: megalinter/megalinter:v5
  script: [ "true" ]
  variables:
    # All available variables are described in documentation
    # https://megalinter.github.io/configuration/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: main
    VALIDATE_ALL_CODEBASE: "true"
    MEGALINTER_CONFIG: ".mega-linter.yml"
    REPORT_OUTPUT_FOLDER: "report"
    # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week  
````

But when the job is running, linter doesn't run
![tempsnip](https://user-images.githubusercontent.com/77079879/144302973-f188f93f-1ab1-467f-85d3-4b653ded1293.png)

Tested the docker image by running locally and it worked by running the linter and generating the report.

Could someone suggest what am I missing ?

**Comment by nvuillam** [comment]
Please can you try the following config and tell what happens ? ?

```yaml
# MegaLinter GitLab CI job configuration file
# More info at https://megalinter.github.io/

megalinter:
  stage: test
  # You can override MegaLinter flavor used to have faster performances
  # More info at https://megalinter.github.io/flavors/
  image: megalinter/megalinter:v5
  script: [ "true" ]
  variables:
    # All available variables are described in documentation
    # https://megalinter.github.io/configuration/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: main
  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week
```

**Comment by guruvamsichintala5** [comment]
Thanks @nvuillam for the quick response. 

Still not running the linters.
![image](https://user-images.githubusercontent.com/77079879/144304956-ff847759-c33b-4539-bc66-751e8f56e9f4.png)
![image](https://user-images.githubusercontent.com/77079879/144304992-e1a507de-7b4f-4e06-8a1d-361557c6c339.png)

**Comment by nvuillam** [comment]
Is it a public or private gitlab runner ?
If a private one, is docker installed and docker daemon running on it ?

**Comment by guruvamsichintala5** [comment]
private gitlab runner with docker installed. And we run our day to day GitlabCI in the same runner

**Comment by nvuillam** [comment]
This is an exact config that worked today on a similar config (private gitlab on premise + private runners)

This is using MegaLinter v4, please can you check ? at least we'll know if it can be related to MegaLinter v5 :)

```yaml
check_quality:
  stage: build
  tags:
    - ubuntu
  only:
    - merge_requests
    - web
  except:
    variables:
      - $SCRATCH_ORG_POOL == "true"
  image: nvuillam/mega-linter-salesforce:latest
  script: ["true"]
  variables:
    # All available variables are described in documentation
    # https://nvuillam.github.io/mega-linter/configuration/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: master
    # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week
```
