### ISSUE TITLE
Docker image missing /usr/bin/shellcheck

### ISSUE THREAD

**Issue by stephenbmfj** [megalinter/megalinter#1136]
The `megalinter/megalinter:v5` docker image is missing `/usr/bin/shellcheck`, which is needed by at least one linter (i.e.: actionlint).

To reproduce:

1. Create `.github/workflows/test.yml`
2. `docker run -v /var/run/docker.sock:/var/run/docker.sock:rw -v $PWD:/tmp/lint:rw -e ENABLE_LINTERS=ACTION_ACTIONLINT`
3. See error

        fatal error while checking tmp/lint/.github/workflows/test.yml: `/usr/bin/shellcheck ...

**Comment by nvuillam** [comment]
Do you have the same issue with megalinter/megalinter:beta ?

Is it related to https://github.com/rhysd/actionlint/issues/98 ? If the problem is from actionlint, can't do a lot
But if you need spellcheck as an option dependency, you may define a PRE_COMMAND in your .mega-linter.yml to install it 

What is this spellcheck app ? there are a lot in github / google, I don't know which one your refer to :/

Example:
```yaml
PRE_COMMANDS:
  - command: npm install eslint-plugin-whatever
    cwd: "root"        # Will be run at the root of MegaLinter docker image
```
