### ISSUE TITLE
Bitbucket Pipeline Support

### ISSUE THREAD

**Issue by Zerotask** [megalinter/megalinter#1324]
**Is your feature request related to a problem? Please describe.**
In my company we're using Bitbucket. It would be great if MegaLinter would support it out of the box

**Describe the solution you'd like**
Provide a similar solution as for GitHub Actions

**Describe alternatives you've considered**
Install and run it inside a Bitbucket Pipeline Container similar as I would do locally

**Additional context**

- https://support.atlassian.com/bitbucket-cloud/docs/what-are-pipes/
- https://support.atlassian.com/bitbucket-cloud/docs/write-a-pipe-for-bitbucket-pipelines/

**Comment by nvuillam** [comment]
I'm not familiar with bitbucket but I'm pretty sure than we could build a default pipeline script that would run MegaLinter and store the results as an artefact :)

Would you like to try and communicate the configuration, or even make a PR ?
All you need is to say that a job depends on docker image megalinter/megalinter:v5 and upload as artifacts the results that are stored in folder /report

See examples for [Gitlab](https://megalinter.github.io/latest/installation/#gitlab) and [Azure](https://megalinter.github.io/latest/installation/#azure-pipelines) ( Gitlab example is probably better about docker image cache management

**Comment by nvuillam** [comment]
According to the [doc](https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/), it could be a `bitbucket-pipelines.yml` file like:

```yaml
pipelines:
  custom:
    megaLinter:
      - step:
          name: Run MegaLinter
          image: megalinter/megalinter:v5
          script:
            - export DEFAULT_WORKSPACE=$BITBUCKET_WORKSPACE && entrypoint.sh
          artifacts:
            - report/**
```

**Comment by Doommius** [comment]
@nvuillam working for bitbucket here, Just leaving it here for now in case others come looking for it. Should possibly be added to the docs :)  BITBUCKET_WORKSPACE is the org name :) 
```
    - step:
        name: Run MegaLinter
        image: oxsecurity/megalinter
        script:
          - export DEFAULT_WORKSPACE=$BITBUCKET_CLONE_DIR && bash /entrypoint.sh
        artifacts:
          - report/**
```
