### ISSUE TITLE
How to make alive status codes 200/203 (markdown link check) expected behavior for MegaLinter?

### ISSUE THREAD

**Issue by bengeset96** [megalinter/megalinter#1368]
Hello project maintainers and contributors, 

Using this awesome toolbox in ADO. 

Previously when using markdown link check standalone without MegaLinter you could do something like this in a config.json file:

`{
  "aliveStatusCodes": [
    200,
    203
  ]
}`

Then in the YML:

        # - script: |
        #     docker pull github/markdown-link-check:stable
        #     docker run -e RUN_LOCAL=true -e config-file='.azuredevops/actions-config/config.json' -v $(System.DefaultWorkingDirectory):/tmp/lint github/markdown-link-check
        # displayName: 'Check for broken URLs'

How to enforce the same behavior when using MegaLinter?

Currently YML is like this example:

```
jobs:
  - job: verify_markdown
    timeoutInMinutes: 10
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          releaseType: stable

      - script: |
          docker pull megalinter/megalinter:v5
          docker run -v $(System.DefaultWorkingDirectory):/tmp/lint -e GIT_AUTHORIZATION_BEARER=$(System.AccessToken) megalinter/megalinter:v5
   displayName: 'Code Scan using GitHub MegaLinter'

     # Publish the Anchore report as an artifact to Azure Pipelines
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: MegaLinter Report'
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/report/'
          ArtifactName: MegaLinterReport  
```
.mega-linter.yml in the root of repository is like this:
```
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
# DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
```
I see that it is possible to disable it in configuration file for MegaLint like. 

`DISABLE_LINTERS: MARKDOWN_MARKDOWN_LINK_CHECK`

Then its off completely and that is not optimal. 

I have tried to search documentation for this, but can't find it. Help me out and I would be really grateful =)

/Benjamin
