### ISSUE TITLE
Set branches for MegaLinter, default behavior and customization unclear. Azure pipelines config generation not implemented yet

### ISSUE THREAD

**Issue by bengeset96** [megalinter/megalinter#1372]
Hello project maintainers and contributors, 

Thanks for merging my last wanted feature so fast. 

I am trying to find documentation on how MegaLinter is handling branches. 

When using:

`npx mega-linter-runner --install`

Two options are given, either main or master.

![image](https://user-images.githubusercontent.com/99641908/161008289-d71e4de1-356e-4d15-952e-7c34a5178329.png)

Neither of them give me updated .mega-linter.yml, i can't see the difference. 

Is this some sort of automagic underneath the bonnet or me that frankly just haven't found the documentation for it? 

Usecase:

Going to use MegaLinter as build validation before feature-branches are allowed to merge into main in ADO. They must lint cleanly with MegaLinter. 

For now ADO config generation is not implemented yet. 

![image](https://user-images.githubusercontent.com/99641908/161009783-278d20ff-bd81-40bf-8cf8-f4080b415dde.png)

If MegaLinter is only targeting main or master, it will not be able to test against feature-branches?

I see in the GH example this is being used:

```
on:
  # Trigger mega-linter at every push. Action will also be visible from Pull Requests to main
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [master, main]
```

```
    # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.github.io/flavors/
        uses: megalinter/megalinter@v5
        env:
          # All available variables are described in documentation
          # https://megalinter.github.io/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ADD YOUR CUSTOM ENV VARIABLES HERE OR DEFINE THEM IN A FILE .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
          # DISABLE: COPYPASTE,SPELL # Uncomment to disable copy-paste and spell checks
```
Here I can see that the great project contributors have made so MegaLint will check against the new commits that is in the PR from feature branch/s against the current main branch (i believe). 

Is this the idea behind it to make it work like that to have MegaLint understand what is outside main?

Would be nice to see some example ADO config file how to make this work (=

/Benjamin

**Comment by nvuillam** [comment]
Azure pipelines config is available in the documentation -> https://megalinter.github.io/latest/installation/#azure-pipelines

About master or main, it's for:
- filtering the PR target branches that will trigger MegaLinter
- triggering MegaLinter when there is a push to the main branch

but you are totally free to remove the constraint and use it for every PR :)

I agree it would be nice to add automatic generation of `azure-pipelines.yml` but the installer, I'll do that someday, or maybe you'd like to make a pull request ?

- azure-pipelines should be defined here -> https://github.com/megalinter/megalinter/tree/main/mega-linter-runner/generators/mega-linter/templates
- installer code to update is here -> https://github.com/megalinter/megalinter/blob/15d6f504e0258c1bdcf1ed34bf884d668e864784/mega-linter-runner/generators/mega-linter/index.js#L249

**Comment by bengeset96** [comment]
Thanks @nvuillam 

It's the same as I have now. 

I'm currently playing with MegaLinter and trying to find a way with ADO for making it nice in CI/CT/CD perspective. 

Pull request can be done when I have the confidence that I have found a good solution (if I will find one hehe). 

For now I am doing in this way. Sharing it here so somebody else might can use it or if they are using the search function in the MegaLinter repository. Pipeline that is running based on a cron job and doing the whole code base. Based on documentation it seems like default branch for MegaLinter is HEAD and in ADO HEAD is main by default. 

So that means that MegaLint should run against main branch daily. Can also use -e VALIDATE_ALL_CODEBASE=false, but the disadvantage then is over time things can change. So perhaps code that were marked as healty before, is not healty more due to newer version, changes underneath the bonnet etc.

```
`# Re-usable pipeline job to perform/detect linting and security issues.
schedules:
  - cron: "0 7 * * *"
    displayName: Daily Good Morning Build
    branches:
      include:
        - main
    always: true

jobs:
  - job: CodeReview
    timeoutInMinutes: 20
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          releaseType: stable

      - script: |
          docker pull megalinter/megalinter:beta
          docker run -v $(System.DefaultWorkingDirectory):/tmp/lint -e GIT_AUTHORIZATION_BEARER=$(System.AccessToken) megalinter/megalinter:beta
        displayName: "Code Review using MegaLinter"

      # Publish the Anchore report as an artifact to Azure Pipelines
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Code Review Report"
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/report/"
          ArtifactName: CodeReviewReport`
```

Also for PR I have found that ADO has one nice functionality under branch policies for branches, in this case main. Here you can see it will trigger the same pipeline when PR and will pre-merge the changes. This will let the functionality of MegaLinter per default work, since then MegaLinter can now run against pre-merged commits as well. Which means it will see the planned upcoming new code. If MegaLinter output is not with good hygiene, the PR will fail and will not merge to main. 

![image](https://user-images.githubusercontent.com/99641908/161147189-cbb1ba23-b1c3-4c16-ac37-a4f841ee3ddf.png)

Result. PR could not merge and there is some stuff I have to fix in my poor written code base. 

![image](https://user-images.githubusercontent.com/99641908/161149936-849c14f7-c3b0-4a31-8118-e046b4a47306.png)


This is nice because it lets you have one single pipeline that is for checking the code base in general daily and use the same pipeline for PR. 

Can also configure two pipelines. One pipeline for just cron job and another one for branch policy for PR with for -e VALIDATE_ALL_CODEBASE=false. Then it will only check the differences in the PR and not the whole codebase, but this is a personal preference/strategy. For me I'd like to have whole codebase clean with good hygiene, even if it has nothing with my specific PR to do.
