### ISSUE TITLE
Sample for "apply fixes" using GitLab CI

### ISSUE THREAD

**Issue by jokay** [megalinter/megalinter#1373]
Is there any sample (`.gitlab-ci.yml`) for using [apply fixes](https://megalinter.github.io/latest/configuration/#apply-fixes) on a self-hosted GitLab?

```yml
megalinter:
  image: megalinter/megalinter-documentation:v5.10.0
  script: ["true"]
  variables:
    APPLY_FIXES: "all"
    DEFAULT_WORKSPACE: ${CI_PROJECT_DIR}
    LINTER_RULES_PATH: .gitlab/linters
    VALIDATE_ALL_CODEBASE: "true"
  artifacts:
    paths:
      - report
    expire_in: 1 hour
```

`APPLY_FIXES_EVENT` and `APPLY_FIXES_MODE` are only valid for **GitHub** but not **GitLab**.
