### ISSUE TITLE
General Question on using Docker linting of flavor megalinter/megalinter-ci_light:v5

### ISSUE THREAD

**Issue by romelBen** [megalinter/megalinter#1425]
Hello! I love this project which helps me out in daily activities such as linting and security compliance. I am running into a wall when I want to incorporate linting for my Dockerfile's. So pretty much this is how it goes. I have my Dockerfiles in a directory but I only want to target specific file names such as `dev-dind-aws.Dockerfile` or `data-dind-aws.Dockerfile` when running linting. When running this on GitLab CI. It does not process through. It basically skips this process. My code is like so:

```
devops-dock-image_lint:
  stage: Docker Lint
  extends: .docker-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "foobar/**/*"
        - "bars/**/*"
        - "monkey/**/*"
        - "donkey/**/*"
  variables:
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR/docker
  script: ["true"] # if script: ["true"] does not work, you may try ->  script: [ "/bin/bash /entrypoint.sh" ]
```

How would I go about **only** targeting one file? I can see environment variables like `DOCKERFILE_HADOLINT_FILE_NAMES_REGEX` being of use but is there any easier way of targeting specific files when using Docker linting in mega-linter?

Thanks for reading my post!
