### ISSUE TITLE
MegaLinter can't access repo, stderr: 'fatal: unable to access 'https://dev.azure.com/{organization}/Platform/_git/Platform/': The requested URL returned error: 400

### ISSUE THREAD

**Issue by bengeset96** [megalinter/megalinter#1515]
**Describe the bug**
MegaLinter can't find the repo. The URL it is trying to access is not valid and will return 404.

**To Reproduce**
```
  - script: |
      docker pull megalinter/megalinter:v5
      docker run -v $(System.DefaultWorkingDirectory):/tmp/lint -e GIT_AUTHORIZATION_BEARER=$(System.AccessToken) megalinter/megalinter:v5
    displayName: 'MegaLinter analysis'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: MegaLinter Report'
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/report/'
        ArtifactName: MegaLinterReport
```

**Expected behavior**
MegaLinter should be able to find the repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/99641908/172344582-dda986f8-c244-4641-b309-ea046c35c6a3.png)

**Additional context**
New repo, haven't had this issue on other repo's. Also tried with MegaLinter beta.
