### ISSUE TITLE
Mega Linter and pre-commit hooks

### ISSUE THREAD

**Issue by milica-nikolic** [megalinter/megalinter#569]
Hi everyone!

I'm curious is there a way to configure mega-linter so it can be combined with git hooks for pre-commits ? I would like to lint only updated files before commits and after that mega-linter would lint whole project while he is implemented in CI tool ?

Thank you in advance ! :)

**Comment by nvuillam** [comment]
Mega-Linter relies on a docker image, so it may be heavy to do a `docker run` every time you want to commit, it's probably best to let CI servers do that for you :)

But if you really want to do that... I could consider creating a [pre-commit hook](https://pre-commit.com/index.html#new-hooks) based on mega-linter-runner :) Or maybe you'd like to do so ?

**Comment by tpansino** [comment]
@milica-nikolic , here's an example `.pre-commit-config.yaml` I use to run the docker image via pre-commit:

```
repos:
 - repo: local
    hooks:
      - id: mega-linter
        name: Mega-Linter
        language: docker_image
        pass_filenames: false
        entry: "-u root -e DEFAULT_WORKSPACE=/src nvuillam/mega-linter:v4.34.0"
```

Notes:
- I also include `REPORT_OUTPUT_FOLDER: /src/.mega-linter` in my `.mega-linter.yml` config. This combined with the `-e DEFAULT_WORKSPACE=/src` makes it so you can view the linter reports outside of the Docker container, after pre-commit finishes. Be sure to also `.gitignore` the `.mega-linter` folder though, or else MegaLinter tries to lint the code samples in the reports. 😄 
- The container version is set manually in the `entry:`, whish is what I recommend instead of using `latest`, Docker doesn't pull from `latest` automatically on updates, because Docker thinks `latest` is just an ordinary tag, and sees it in the cache. Setting an explicit version busts the cache and makes Docker update the image, transparent to users.

@nvuillam I planned to write these instructions up someday and make them part of the docs, just haven't had time yet 😄

**Comment by nvuillam** [comment]
That's great news, thanks :)

**Comment by milica-nikolic** [comment]
I had different approach. I have used dotnet format tool in pre commit script so I can fix errors that mega-linter reported in GitLab CI pipeline.

Your approach is way better and I will look deeper into that.

You mentioned that you plan to write instructions, please link them when you finish them. I am sure that they will be quite helpful.

Thank you for help! 😃

**Comment by Kurt-von-Laven** [comment]
It would be awesome to add a .pre-commit-hooks.yaml to mega-linter so that downstream projects can merely reference this repo and the mega-linter hook id without having to be as clever as @tpansino. @nvuillam, how close is the excerpt above to what would be needed?

**Comment by nvuillam** [comment]
I'm not a pre-commit user (I like my commits to just commit :p ), so I'm not familiar with this tool ....

I'm also afraid that running a docker image during a pre-commit hook may be not very user friendly ... but for those who really want to do it, @tpansino maybe you could implement this famous `.pre-commit-hooks.yaml` ? 👼

**Comment by Kurt-von-Laven** [comment]
I looked through [pre-commit's instructions for running an existing docker_image](https://pre-commit.com/#docker_image), and believe the essence of what would be needed is below. One would need some mechanism by which to ensure that the version of the Docker image stayed in sync with the version of the GitHub repository itself.

```yaml
-   id: mega-linter
    name: Run Mega-Linter
    language: docker_image
    entry: nvuillam/mega-linter:<version>
```

**Comment by Kurt-von-Laven** [comment]
@nvuillam, is there some mechanism by which one could run Mega-Linter only on the files passed to it? One of pre-commit's big selling points is how much faster it runs than traditional CI since most linters only need to consider the staged files that it passes to them by default. Even on a small code base with a specific flavor, commits take multiple minutes. Also, do you happen to know off the top of your head why root is needed? Not sure if that is a consequence of the way pre-commit runs Docker containers.

**Comment by nvuillam** [comment]
Hmmmm there is not, but it can probably be done by sending the list of files as argument :)

At the moment Mega-Linter list files, we could do something like:
if MEGALINTER_FILES_TO_LINT
    files_to_lint = MEGALINTER_FILES_TO_LINT
else
    usual way

**Comment by Kurt-von-Laven** [comment]
I opened a separate feature request to support linting passed files based on this discussion in case someone can beat me to it.

> About root, no idea... it was like that on Super-Linter ^^

I believe I figured this part out however. We recently released [rootless-docker](https://github.com/marketplace/actions/rootless-docker), a simple GitHub Action that discusses what I believe is going on here.

> One would need some mechanism by which to ensure that the version of the Docker image stays in sync with the version of the GitHub repository itself.

As for this piece, the Python-based [Commitizen](https://commitizen-tools.github.io/commitizen/config/) takes a `version_files` argument, so I believe one could wire up their [bump-version Action](https://commitizen-tools.github.io/commitizen/tutorials/github_actions/), and specify `.pre-commit-hooks.yaml` as a version file.

**Comment by tpansino** [comment]
Apologies, I've been really busy and am catching up on this thread.

@Kurt-von-Laven, the example in your previous message is a proposed `.pre-commit-hooks.yaml`, yes? Have you actually gotten it to work? I just forked and tried it and it's not working for me.

I too tried implementing a pre-commit hook this way back in March, until I encountered https://github.com/pre-commit/pre-commit/issues/1858. Basically for Node execution, pre-commit expects a `package.json` to be in the top-level folder of the repo, and Mega Linter's is in the `mega-linter-runner` sub-folder. The maintainer doesn't want to support any customization there as you can see from the discussion, so if you've found a way around that limitation - great!

Otherwise, I meant to eventually ask @nvuillam what it would take to split the `mega-linter-runner` into it's own repo? Or perhaps we could just create a shim repo that meets the interface requirements for pre-commit to be able to install and run Mega Linter?

FWIW - I'm using Mega-Linter extensively these days via Pre-commit, and with [this](https://github.com/pre-commit/action) (deprecated 😞) GitHub Action to enable a consistent UX between local and CI/CD pipeline. It allows for maintaining a single config for linting enforcement on the CI/CD, but faster feedback for users that install the pre-commit hook if they want. I love it, and I'm happy to help test any pre-commit integration out to better enable the pattern ❤️

**Comment by nvuillam** [comment]
@Kurt-von-Laven @tpansino 

As I have automation that updates source of both mega-linter and mega-linter-runner, I'd rather use the mirror repos solution :)

I'm in a train, i'll try to initialize that until I arrive ^^

**Comment by tpansino** [comment]
@Kurt-von-Laven if you've got the time to put something together, I'm happy to review. Otherwise it's going on my backlog 😆

CC @TimPansino - this effort might interest you.

**Comment by Kurt-von-Laven** [comment]
I'll take a stab at mirroring mega-linter-runner at some point in the next few weeks. I realized that I somehow must have changed something related to our yamllint config, so I removed my caveat about that to avoid discouraging people from using a perfectly good pre-commit hook in the meantime.

**Comment by Kurt-von-Laven** [comment]
I have tested this out for a bit now, and indeed incremental mode is supported at v5. Here is a sample config that demonstrates how you would disable a slow-running linter such as jscpd, which necessarily must always run on all files since it detects duplication, on commit but not push.

```yaml
      - id: mega-linter
        name: Run .NET flavor of Mega-Linter (skipping jscpd)
        entry: mega-linter-runner
        language: node
        pass_filenames: false
        args:
          - --flavor
          - dotnet
          - --env
          - LOG_LEVEL=warning
          - --env
          - VALIDATE_ALL_CODEBASE=false
          - --env
          - DISABLE_LINTERS=COPYPASTE_JSCPD
          - --release
          - v5
          - --fix
        stages:
          - commit
        additional_dependencies:
          - mega-linter-runner@v5
      - id: mega-linter
        name: Run .NET flavor of Mega-Linter
        entry: mega-linter-runner
        language: node
        pass_filenames: false
        args:
          - --flavor
          - dotnet
          - --env
          - LOG_LEVEL=warning
          - --env
          - VALIDATE_ALL_CODEBASE=true
          - --release
          - v5
          - --fix
        stages:
          - push
        additional_dependencies:
          - mega-linter-runner@v5
```
