### ISSUE TITLE
Unexpected error: Cannot read property 'totalFoundErrorNumber' of undefined

### ISSUE THREAD

**Issue by nsavelyeva** [megalinter/megalinter#712]
**Describe the bug**
Using GitHub Actions, Groovy linter fails with the below error on every Groovy file:
`Unexpected error: Cannot read property 'totalFoundErrorNumber' of undefined`.
Locally this error is not reproduced.

**To Reproduce**

1. Have a maven project with some groovy files.
2. Create a GitHub Action workflow, in my case I configured the job as follows:
```
jobs:
  cancel_duplicates:
    name: Cancel duplicate jobs
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  build:
    name: Mega-Linter src/main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Mega-Linter
        id: ml
        uses: nvuillam/mega-linter@v4
        env:
          ENABLE: GROOVY
          GROOVY_NPM_GROOVY_LINT_ARGUMENTS: '--output report/megalinter-src-main.html'
          GROOVY_NPM_GROOVY_LINT_CONFIG_FILE: .groovylintrc-src-main.json
          GROOVY_NPM_GROOVY_LINT_RULES_PATH: conf
          GROOVY_NPM_GROOVY_LINT_FILTER_REGEX_INCLUDE: src/main
          PRINT_ALPACA: false
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
3. Trigger the GitHub Action and wait until it gets completed.
4. Open checks tab as shown in the screenshot below.
5. See the `totalFoundErrorNumber` error on every file

**Expected behavior**
GitHub Actions produce no `totalFoundErrorNumber` errors, and has the same output as the local execution.

**Screenshots**
![Screenshot 2021-09-01 at 11 12 02](https://user-images.githubusercontent.com/21998320/131645592-f12f0433-7a12-4d30-950d-4c293c4808d2.png)

**Additional context**
- For local execution I use the same parameters:
```
npx mega-linter-runner -r insiders -e 'ENABLE=GROOVY' -e 'GROOVY_NPM_GROOVY_LINT_FILTER_REGEX_INCLUDE=src/main' -e 'GROOVY_NPM_GROOVY_LINT_CONFIG_FILE=conf/.groovylintrc-src-main.json' -e 'GROOVY_NPM_GROOVY_LINT_RULES_PATH=conf' -e 'PRINT_ALPACA=false' -e 'SHOW_ELAPSED_TIME=true'
``` 
- I found a similar error in [this closed issue](https://github.com/nvuillam/npm-groovy-lint/issues/107).
