### ISSUE TITLE
Add `nixfmt` Nix format linter

### ISSUE THREAD

**Issue by samcraigdev** [megalinter/megalinter#736]
Would love to have `nixfmt` supported natively via the [nvuillam/mega-linter](https://hub.docker.com/r/nvuillam/mega-linter) Docker image.

Here's a reference to the plugin setup we're using at the moment, also linked [here](https://github.com/growthatco/mega-linter-plugins/blob/main/plugins/mega-linter-plugin-nixfmt/nixfmt.megalinter-descriptor.yml):
```yaml
descriptor_id: NIX
descriptor_type: format
file_extensions:
  - ".nix"  
linters:
  - linter_name: nixfmt
    linter_repo: https://github.com/serokell/nixfmt
    linter_url: https://nixfmt.serokell.io/
    is_formatter: true
    cli_lint_extra_args:
      - "--check"
    cli_lint_fix_arg_name: "--width=100"
    cli_lint_fix_remove_args:
      - "--check"
    examples:
      - "`nixfmt < input.nix` – reads Nix code form stdin, formats it, and outputs to stdout"
      - "`nixfmt file.nix` – format the file in place"
    install:
      dockerfile:
        - RUN apk add  \
            --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/main \
            --update --no-cache \
            bash \
            boost-dev \
            curl \
            sudo \
            tar \
            xz
        - RUN apk add  \
            --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
            --update --no-cache nix
        - RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        - RUN nix-channel --update
        - RUN rm -rf /nix/var/nix/profiles/default
        - RUN ln -s /nix/var/nix/profiles/per-user/root /nix/var/nix/profiles/default
        - RUN nix-env -iA nixpkgs.nixfmt
        - RUN ln -s /nix/var/nix/profiles/default/bin/nixfmt /usr/bin
        - RUN nixfmt --version
```
