### ISSUE TITLE
[TEXT_REPORTER] Get Artifacts on GitHub Actions - confusing

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#802]
Even if it's good explains on [Text Reporter](https://github.com/nvuillam/mega-linter/blob/v4.46.0/docs/reporters/TextReporter.md) section of documentation, with screenshots, there is a situation where it's still confusing.

When you said "Get Artifacts on GitHub Actions", could you confirm that it's only on Pull Request condition ?

Because when I try to found artifacts on standard GA run [push](https://github.com/llaville/php-compatinfo-db/blob/master/.github/workflows/php-tests.yaml#L5), I found nothing !

![ga_artifact](https://user-images.githubusercontent.com/364342/135723654-a53926c0-69a1-40f0-b416-2e816401da6b.png)

**Comment by nvuillam** [comment]
That's quite strange ^^

**Comment by llaville** [comment]
Is it normal (for you) to make `REPORT_OUTPUT_FOLDER` (`report/`) folder with root account ?

i.e:
```
drwxr-xr-x  5 root     root      4096 Sep  9 10:49 report/
```

**Comment by nvuillam** [comment]
@llaville you need to add upload artifacts step [in your GHA definition](https://github.com/llaville/php-compatinfo-db/blob/5c22199b3e7c76dfa3564b492e6dbeea495e7177/.github/workflows/php-tests.yaml#L58) :)

```
      # Upload Mega-Linter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Mega-Linter reports
          path: |
            report
            mega-linter.log
```
