### ISSUE TITLE
Use concurrency option of GH actions to cancel previous workflow runs

### ISSUE THREAD

**Issue by lars-reimann** [megalinter/megalinter#920]
**Is your feature request related to a problem? Please describe.**
This is a follow-up to #622, i.e. about cancelling previous workflow runs when a new push to a branch occurs.

**Describe the solution you'd like**
GitHub actions directly offers a means to prevent [concurrent workflow runs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) and [concurrent job runs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency) and to cancel any previous runs.

**Advantages:**
* It's not another job, so
  * cancellation happens faster,
  * it does not show up as a check in PRs,
  * you don't get billed for it.
* Not entirely sure about this, but I think you don't get notified (e.g. by mail) about cancelled runs.

**Disadvantages:**
* [skip-duplicate-actions](https://github.com/fkirc/skip-duplicate-actions) offers more options.
* One needs to be careful that only the mega-linter workflow is cancelled by assigning a unique concurrency group.

**Example:**

```yml
name: Mega-Linter

on:
  pull_request:
    branches: [main]

# Workflow can only run once per branch and any previous pending or in-progress runs are cancelled.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit
  FILTER_REGEX_EXCLUDE: (\.github/workflows/)

jobs:
  lint:
    # As usual...
```

**Describe alternatives you've considered**
Keep everything as is, which is also perfectly acceptable (so feel free to close this).

**Additional context**
Links (same as above):
- [Workflow concurrency](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency)
- [Job concurrency](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency)
