### ISSUE TITLE
flake8 plugins and annotations 

### ISSUE THREAD

**Issue by elisim** [megalinter/megalinter#952]
Hi,

Is it possible to add flake8 plugins? Like in https://github.com/julianwachholz/flake8-action/issues/22.
In addition, does megalinter can provide annotations? 

See also:
https://github.com/julianwachholz/flake8-action-test/pull/1/files

![image](https://user-images.githubusercontent.com/17675462/140757450-a97033c2-01af-4454-a895-69293367e528.png)

Thank you

**Comment by nvuillam** [comment]
Name the flake8 plugins you'd like and we probably can include them in core MegaLinter if they are widely used :)

Meanwhile, it is also possible to use https://megalinter.github.io/configuration/#pre-commands[PRE_COMMANDS]() to install missing plugins

Example to add in your .megalinter.yml local config file

```yaml
PRE_COMMANDS:
  - command: pip install pep8-naming==0.12.1 flake8-comprehensions==3.6.1
    cwd: "root"    
```
